using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace ProjectEuler
{
    public static class _002
    {
        // TITLE: Even Fibonacci numbers

        // DESCRIPTION: Each new term in the Fibonacci sequence is generated by 
        // adding the previous two terms. By starting with 1 and 2, the first 10 
        // terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        // OBJECTIVE: By considering the terms in the Fibonacci sequence whose values 
        // do not exceed four million, find the sum of the even-valued terms.

        public static void DoWork(int limit)
        {
            Stopwatch watch = new Stopwatch();
            watch.Start();

            int smallerDigit = 1;
            int largerDigit = 2;
            int nextDiscovery = 0;
            int sum = 2;

            while (nextDiscovery < limit)
            {
                nextDiscovery = smallerDigit + largerDigit;
                smallerDigit = largerDigit;
                largerDigit = nextDiscovery;

                if (nextDiscovery % 2 == 0)
                {
                    sum += nextDiscovery;
                }
            }

            watch.Stop();

            Console.WriteLine($"002: {sum} in {watch.Elapsed}");
        }
    }
}
